config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :policies

  get 'welcome/homepage'
  root 'welcome#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/policy.rb
class Policy < ApplicationRecord


  def self.locations
    Policy.select("DISTINCT(location)")
  end
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_list.rb
class UserList < ApplicationRecord
end

app/models/vote.rb
class Vote < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
	def new

		@policy = Policy.new
	end


	def index
		@locations = Policy.locations
		if params[:location]
			@policies = Policy.where("LOWER(location) LIKE LOWER (?)", "%#{params[:location]}%")
		else
		@policies = Policy.all
		end
	end


	def create
		@policy = Policy.new(article_params)

		@policy.save
		redirect_back(fallback_location: 'http://localhost:3000/policies')

	end

	def show
		@policy = Policy.find(params[:id])
	end


	private
		def article_params
			params.require(:policy).permit(:title, :description, :policymakers, :location)
		end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def homepage
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/policies/index.html.erb
<div class="nav">
<div class="nav-content">
  <a href="http://localhost:3000/policies">

<svg class="back menu" width="38px" height="24px" viewBox="0 0 19 12" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 49 (51002) - http://www.bohemiancoding.com/sketch -->
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Elections" transform="translate(-20.000000, -23.000000)" fill="#37393A">
            <path d="M20,23 L39,23 L39,25 L20,25 L20,23 L20,23 Z M20,28 L39,28 L39,30 L20,30 L20,28 L20,28 Z M20,35 L20,33 L39,33 L39,35 L20,35 L20,35 Z" id="Shape-Copy"></path>
        </g>
    </g>
</svg></a>

<p class="nav-title">POLICIES</p>
</div>
</div>



	<% @policies.each do |policy| %>
    <%= link_to policy_path(policy) do %>
		<div class="policy-card">
    <div class="date">5 DAYS AGO</div>
    <div class="title">
        <p class="tag">MUNICIPAL</p>
				<p><%= policy.title%></p>
		</div>
    <% end %>
    </div>
  <% end %>


  <%= form_tag policies_path, method: :get, authentication: false, id:'search' do %>

  <%= select_tag :location, options_from_collection_for_select(@locations, 'location', 'location'),:include_blank => true, :onchange => "this.form.submit();" %>

<% end  %>


<% @locations.each do |p| %>
  <a>
    <%= p.location %>
  </a>
  <br>
<% end %>


<%= form_with scope: :policy, url: policies_path,local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

   <p>
    <%= form.label :policymakers %><br>
    <%= form.text_field :policymakers %>
  </p>

  <p>
    <%= form.label :location %><br>
    <%= form.text_field :location %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>


<div>

app/views/policies/show.html.erb
<div class="nav">
<div class="nav-content">
	<a href="http://localhost:3000/policies">
<svg class="back" width="28px" height="48px" viewBox="0 0 14 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 49 (51002) - http://www.bohemiancoding.com/sketch -->
    <desc>Created with Sketch.</desc>
    <defs></defs>
    
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" stroke-linecap="square">
        <g id="Policy-Details" transform="translate(-19.000000, -14.000000)" stroke="#37393A" stroke-width="2">
            <g id="Group" transform="translate(20.000000, 15.000000)">
                <polyline id="Line" points="11.5 0.5 6.95207492 5.04792508 0.988101979 11.011898"></polyline>
                <path d="M11.0000071,21.0238031 L0.988101979,11.011898" id="Line-Copy"></path>
            </g>
        </g>
    </g>
</svg></a>

<p class="nav-title">POLICY DETAILS</p>
</div>
</div>
<div class="policy-head">
  <p class="policymaker"><%= @policy.policymakers%></p>

  <h1 class="title">
  <%= @policy.title %>
  </h1>

</div>

<div class="content">
<p class="description">Description</p>
<p>
  <%= @policy.description %>
</p>
</div>

<div class="voting">
  <p class="reminder">Voting period ends on March 16th</p>
  <div class="btn filled">Submit feedback</div>
</div>

<!-- <a>
	<%= @policy.policymakers%>
	<%= @policy.location%>
</a> -->

app/views/welcome/homepage.html.erb
<h1>Welcome#homepage</h1>
<p>Find me in app/views/welcome/homepage.html.erb</p>